controller_list:
  - name: fake_gripper_controller
    joints:
      - joint_t
  - name: fake_arm_controller
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b