controller_list:
  - name: fake_arm_controller
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t
initial:  # Define initial robot poses.
  - group: arm
    pose: home