# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# joint_limits:
#   joint_b:
#     has_velocity_limits: true
#     max_velocity: 0.5 #3.8135445205
#     has_acceleration_limits: false
#     max_acceleration: 0
#   joint_e:
#     has_velocity_limits: true
#     max_velocity: 0.5 #3.31612567
#     has_acceleration_limits: false
#     max_acceleration: 0
#   joint_l:
#     has_velocity_limits: true
#     max_velocity: 0.5 #3.31612567
#     has_acceleration_limits: false
#     max_acceleration: 0
#   joint_r:
#     has_velocity_limits: true
#     max_velocity: 0.5 #3.31612567
#     has_acceleration_limits: false
#     max_acceleration: 0
#   joint_s:
#     has_velocity_limits: true
#     max_velocity: 0.5 #3.31612567
#     has_acceleration_limits: false
#     max_acceleration: 0
#   joint_t:
#     has_velocity_limits: true
#     max_velocity: 0.5 #5.8032199225
#     has_acceleration_limits: false
#     max_acceleration: 0
#   joint_u:
#     has_velocity_limits: true
#     max_velocity: 1
#     has_acceleration_limits: false
#     max_acceleration: 0
joint_limits:
  joint_b:
    has_velocity_limits: true
    max_velocity: 3.8135445205
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -1.9198
    max_position: 1.9198
  joint_e:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -2.966
    max_position: 2.966
  joint_l:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -1.9198
    max_position: 1.9198
  joint_r:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -3.1414
    max_position: 3.1414
  joint_s:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -3.1414
    max_position: 3.1414
  joint_t:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -3.1413
    max_position: 3.1413
  joint_u:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    min_position: -1.5707
    max_position: 2.0071