language: generic

cache:
  directories:
    - $HOME/.ccache

services:
  - docker

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros
    - ROS_DISTRO="indigo" ROS_REPO=ros-testing
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-testing
    - ROS_DISTRO="melodic" ROS_REPO=ros
    - ROS_DISTRO="melodic" ROS_REPO=ros-testing

matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo" ROS_REPO=ros
    - env: ROS_DISTRO="indigo" ROS_REPO=ros-testing
    - env: ROS_DISTRO="kinetic" ROS_REPO=ros-testing
    - env: ROS_DISTRO="melodic" ROS_REPO=ros-testing

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
